steps:
- task: Npm@1
  displayName: 'Install TypeScript'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install typescript'
- powershell: npx tsc --skipLibCheck --skipDefaultLibCheck --noLib -p .
  displayName: 'Run type check'
